spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spice_shop
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # Or your preferred strategy

  resources:
    static-locations=file:/productImg:
logging:
  level:
    org:
      springframework:
        security=DEBUG:

file:
  upload-dir: classpath:/static/assets/img/product/

server:
  port: 8081

